var rule = {
    title:'荐片',
    host:'https://api2.jpysvip.net',
    homeUrl:'/api/tag/hand?channel=wandoujia&code=unknown601193cf375db73d',
    url:'/api/crumb/list?channel=wandoujia&sort=hot&type=0&category_id=fyclass&page=fypage&year=0&limit=24',
    class_name:'电影&电视剧&动漫&综艺',
    class_url:'1&2&3&4',
    detailUrl:'/api/node/detail?channel=wandoujia&id=fyid',
    searchUrl:'/api/video/search?key=**&page=fypage&channel=wandoujia',
    searchable:2,
    quickSearch:0,
    filterable:0,
    headers:{
        'User-Agent':'jianpian-android/360',
        'JPAUTH':'3TI7PB3K7ACtpudyqV+jrMVNrn6PUkzJj3HxnYhGzXvXfbwBGwOXqjXUk+xwKQeX',
        'x-region-channel':'wandoujia',
        'x-region-code':'CN'
    },
    timeout:5000,
    limit:8,
    play_parse:true,
    play_json:[{
        re:'*',
        json:{
            parse:0,
            jx:0
        }
    }],
    lazy:'',
    图片来源:'@Referer=www.jianpianapp.com@User-Agent=jianpian-version353',
    推荐:'json:data;title;cover;area;id',
    一级:'json:data;title;cover;area;id',
    二级:{
        title:'data.title',
        desc:'data.area;data.type;data.year;data.score;data.duration',
        img:'data.cover',
        content:'data.description',
        is_json:1,
        tabs:'js:TABS=[];if(html.data.have_ftp_ur == 1){TABS.push("超清")}if(html.data.have_m3u8_ur == 1){TABS.push("普清")}',
        lists:'js:log(TABS);LISTS=[];TABS.forEach(function(tab){if(/超清/.test(tab)){let ftp=html.data.new_ftp_list;let d=ftp.map(function(it){return it.title+"$"+it.url});LISTS.push(d)}else if(/普清/.test(tab)){let m3u=html.data.new_m3u8_list;let d=m3u.map(function(it){return it.title+"$"+it.url});LISTS.push(d)}});',
    },
    搜索:'json:data;title;cover;area;id',
}
